In [38]:
import numpy as np

In [39]:
# to create an array 
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [40]:
type(a)

numpy.ndarray

In [41]:
# performing operations on array
print(a + b)
print(a - b)
print(a * b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [42]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [43]:
# creating 3D array
a3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,4,15],[16,17,18]] ])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13  4 15]
  [16 17 18]]]


In [44]:
# to get the orader of array
print(a2.shape)

(2, 3)


In [45]:
print(a3.shape)

(3, 2, 3)


In [46]:
# to know the dimensin of the array
print(a2.ndim)
print(a3.ndim)

2
3


In [47]:
# to know the datatype of elements
print(a2.dtype)
print(a3.dtype)
print(a.dtype)

int64
int64
int64


In [48]:
# a range method to make an array into a given range
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [51]:
np.random.randint(1,11, size = (2,3))

array([[ 1, 10,  3],
       [ 7,  5,  3]], dtype=int32)

In [52]:
np.random.randint(1,11, size = (3,2,3))

array([[[ 3,  6, 10],
        [ 8,  7,  6]],

       [[ 7,  6,  5],
        [ 3,  4,  7]],

       [[ 4,  1,  4],
        [ 2, 10,  3]]], dtype=int32)

In [53]:
x = np.random.randint(1,21, size = (2,2))
y = np.random.randint(1,21, size = (2,2))
print(x)
print(y)

[[17  4]
 [13 17]]
[[19 18]
 [12  7]]


In [54]:
# operations on 2D array
print( x + y)
print(x - y)
print(x * y)

[[36 22]
 [25 24]]
[[ -2 -14]
 [  1  10]]
[[323  72]
 [156 119]]


In [55]:
# matrix multiplication
# 1st method
print( x @ y)

[[371 334]
 [451 353]]


In [56]:
# 2nd Method
np.dot(x,y)

array([[371, 334],
       [451, 353]], dtype=int32)

In [57]:
# multiplication of all the elements of an array
x.prod()

np.int64(15028)

In [58]:
# to find the mean 
x.mean()
y.mean()

np.float64(14.0)

In [59]:
print(x)

[[17  4]
 [13 17]]


In [60]:
# column wise
b = x.mean(axis=0)
print(b)

[15.  10.5]


In [61]:
# row wise
c = x.mean(axis=1)
print(c)

[10.5 15. ]


In [62]:
# operation on array elements
print(x.sum())  # sum 
print(x.std())  # standard deviation
print(x.var)    # variance

51
5.3091901453988255
<built-in method var of numpy.ndarray object at 0x000001BD134BA850>


In [63]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [64]:
arr2 = np.random.randint(11,100,size= (4,4))
print(arr2)

[[45 74 31 20]
 [38 88 65 49]
 [87 12 22 67]
 [63 78 72 36]]


In [65]:
# converting size of a matrix into another size
print('2 X 8')
print(arr2.reshape(2,8))
print('8 X 2')
print(arr2.reshape(8,2))


2 X 8
[[45 74 31 20 38 88 65 49]
 [87 12 22 67 63 78 72 36]]
8 X 2
[[45 74]
 [31 20]
 [38 88]
 [65 49]
 [87 12]
 [22 67]
 [63 78]
 [72 36]]


In [66]:
print(arr2)

[[45 74 31 20]
 [38 88 65 49]
 [87 12 22 67]
 [63 78 72 36]]


In [67]:
print(arr2[0])  #0th row
print(arr2[0,1]) #0th row 1st column 
print(arr2[-1])  # last row
print(arr2[:3]) # 0th to 2nd row
print(arr2[1:]) # 1st to last row

[45 74 31 20]
74
[63 78 72 36]
[[45 74 31 20]
 [38 88 65 49]
 [87 12 22 67]]
[[38 88 65 49]
 [87 12 22 67]
 [63 78 72 36]]


In [68]:
arr2 > 50

array([[False,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True, False]])

In [69]:
y = arr2[arr2 > 50]
z = y.reshape(4,2)
print(z)

[[74 88]
 [65 87]
 [67 63]
 [78 72]]
