In [1]:
import numpy as np

In [5]:
# to create an array 
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [8]:
type(a)

numpy.ndarray

In [11]:
# performing operations on array
print(a + b)
print(a - b)
print(a * b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [13]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [16]:
# creating 3D array
a3 = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,4,15],[16,17,18]] ])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13  4 15]
  [16 17 18]]]


In [19]:
# to get the orader of array
print(a2.shape)

(2, 3)


In [20]:
print(a3.shape)

(3, 2, 3)


In [22]:
# to know the dimensin of the array
print(a2.ndim)
print(a3.ndim)

2
3


In [24]:
# to know the datatype of elements
print(a2.dtype)
print(a3.dtype)
print(a.dtype)

int64
int64
int64


In [28]:
# a range method to make an array into a given range
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [44]:
np.random.randint(1,11, size = (2,3))

array([[2, 8, 6],
       [8, 5, 8]], dtype=int32)

In [45]:
np.random.randint(1,11, size = (3,2,3))

array([[[9, 7, 4],
        [9, 7, 9]],

       [[3, 9, 3],
        [3, 9, 1]],

       [[2, 7, 6],
        [5, 3, 9]]], dtype=int32)

In [46]:
x = np.random.randint(1,21, size = (2,2))
y = np.random.randint(1,21, size = (2,2))
print(x)
print(y)

[[ 2 20]
 [12 19]]
[[16 19]
 [20 13]]


In [50]:
# operations on 2D array
print( x + y)
print(x - y)
print(x * y)

[[18 39]
 [32 32]]
[[-14   1]
 [ -8   6]]
[[ 32 380]
 [240 247]]


In [53]:
# matrix multiplication
# 1st method
print( x @ y)

[[432 298]
 [572 475]]


In [54]:
# 2nd Method
np.dot(x,y)

array([[432, 298],
       [572, 475]], dtype=int32)

In [56]:
# multiplication of all the elements of an array
x.prod()

np.int64(9120)

In [61]:
# to find the mean 
x.mean()
y.mean()

np.float64(17.0)

In [68]:
print(x)

[[ 2 20]
 [12 19]]


In [67]:
# column wise
b = x.mean(axis=0)
print(b)

[ 7.  19.5]


In [66]:
# row wise
c = x.mean(axis=1)
print(c)

[11.  15.5]


In [75]:
# operation on array elements
print(x.sum())  # sum 
print(x.std())  # standard deviation
print(x.var)    # variance

53
7.189401922274203
<built-in method var of numpy.ndarray object at 0x0000019B9EFADD70>


In [82]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [84]:
arr2 = np.random.randint(11,100,size= (4,4))
print(arr2)

[[54 94 38 86]
 [22 99 78 16]
 [78 47 18 54]
 [41 33 49 38]]


In [86]:
# converting size of a matrix into another size
print('2 X 8')
print(arr2.reshape(2,8))
print('8 X 2')
print(arr2.reshape(8,2))


2 X 8
[[54 94 38 86 22 99 78 16]
 [78 47 18 54 41 33 49 38]]
8 X 2
[[54 94]
 [38 86]
 [22 99]
 [78 16]
 [78 47]
 [18 54]
 [41 33]
 [49 38]]
